# Exporting Data

<img src="export_data.jpg" style="width:350px;height:220px"/>

In [1]:
import pandas as pd

## Load data

In [2]:
marvel_hero = pd.read_excel('superhero_info.xlsx',sheet_name='Marvel Comics')
dc_hero = pd.read_excel('superhero_info.xlsx',sheet_name='DC Comics')

In [3]:
hero_dtype = {'name':'string',
              'Gender': 'category',
              'Eye Color': 'string',
              'Race': 'string',
              'Hair Color': 'string',
              'Publisher': 'string',
              'Alignment': 'category'
              }

In [4]:
marvel_hero_newDtype = pd.read_excel('superhero_info.xlsx',sheet_name='Marvel Comics',dtype=hero_dtype)

In [5]:
marvel_hero_newDtype.to_excel('Marvel Hero corrected dtype.xlsx')

In [6]:
marvel_hero_newDtype.to_excel('Marvel Hero corrected dtype_noIndex.xlsx',index=False)

In [7]:
marvel_hero_newDtype.to_pickle('Marvel.pkl')

## Load DC

In [8]:
dc_hero = pd.read_excel('superhero_info.xlsx',sheet_name='DC Comics',dtype=hero_dtype)

In [9]:
dc_hero_cdtype = dc_hero.to_csv('DC Hero cdtype.csv',index=False)

In [10]:
dc_hero_csv = pd.read_csv('DC Hero cdtype.csv')

In [11]:
dc_hero_csv

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Alignment,Weight
0,Abin Sur,Male,blue,Ungaran,No Hair,185,DC Comics,good,90.0
1,Adam Strange,Male,blue,Human,Blond,185,DC Comics,good,88.0
2,Alan Scott,Male,blue,-,Blond,180,DC Comics,good,90.0
3,Alfred Pennyworth,Male,blue,Human,Black,178,DC Comics,good,72.0
4,Amazo,Male,red,Android,-,257,DC Comics,bad,173.0
...,...,...,...,...,...,...,...,...,...
210,Wildfire,Male,-,-,-,-99,DC Comics,good,NaN
211,Wonder Girl,Female,blue,Demi-God,Blond,165,DC Comics,good,51.0
212,Wonder Woman,Female,blue,Amazon,Black,183,DC Comics,good,74.0
213,Zatanna,Female,blue,Human,Black,170,DC Comics,good,57.0
214,Zoom,Male,red,-,Brown,185,DC Comics,bad,81.0

In [12]:
dc_hero_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        215 non-null    object
 1   Gender      215 non-null    object
 2   Eye color   215 non-null    object
 3   Race        215 non-null    object
 4   Hair color  215 non-null    object
 5   Height      215 non-null    int64
 6   Publisher   215 non-null    object
 7   Alignment   215 non-null    object
 8   Weight      144 non-null    float64
dtypes: float64(1), int64(1), object(7)
memory usage: 15.2+ KB

In [13]:
dc_hero.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        215 non-null    string
 1   Gender      215 non-null    category
 2   Eye color   215 non-null    object
 3   Race        215 non-null    string
 4   Hair color  215 non-null    object
 5   Height      215 non-null    int64
 6   Publisher   215 non-null    string
 7   Alignment   215 non-null    category
 8   Weight      144 non-null    float64
dtypes: category(2), float64(1), int64(1), object(2), string(3)
memory usage: 12.6+ KB

In [14]:
marvel_hero_pkl = pd.read_pickle('Marvel.pkl')

In [15]:
marvel_hero_pkl

,name,Gender,Eye color,Race,Hair color,Height,Publisher,Alignment,Weight
0,A-Bomb,Male,yellow,Human,No Hair,203,Marvel Comics,good,441
1,Abomination,Male,green,Human / Radiation,No Hair,203,Marvel Comics,bad,441
2,Abraxas,Male,blue,Cosmic Entity,Black,-99,Marvel Comics,bad,-99
3,Absorbing Man,Male,blue,Human,No Hair,193,Marvel Comics,bad,122
4,Agent 13,Female,blue,-,Blond,173,Marvel Comics,good,61
...,...,...,...,...,...,...,...,...,...
383,X-Man,Male,blue,-,Brown,175,Marvel Comics,good,61
384,Yellow Claw,Male,blue,-,No Hair,188,Marvel Comics,bad,95
385,Yellowjacket,Male,blue,Human,Blond,183,Marvel Comics,good,83
386,Yellowjacket II,Female,blue,Human,Strawberry Blond,165,Marvel Comics,good,52
387,Ymir,Male,white,Frost Giant,No Hair,305,Marvel Comics,good,-99

In [16]:
marvel_hero_pkl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        388 non-null    string
 1   Gender      388 non-null    category
 2   Eye color   388 non-null    object
 3   Race        388 non-null    string
 4   Hair color  388 non-null    object
 5   Height      388 non-null    int64
 6   Publisher   388 non-null    string
 7   Alignment   388 non-null    category
 8   Weight      388 non-null    int64
dtypes: category(2), int64(2), object(2), string(3)
memory usage: 22.4+ KB

In [17]:
marvel_hero = pd.read_excel('superhero_info.xlsx',sheet_name='Marvel Comics',dtype=hero_dtype)
dc_hero = pd.read_excel('superhero_info.xlsx',sheet_name='DC Comics',dtype=hero_dtype)

In [18]:
marvel_hero.to_pickle('Marvel Hero.pkl')
dc_hero.to_pickle('DC Hero.pkl')